#!/bin/bash

# Guión generado automáticamente por './volcarWiki.sh 2' por antonio@Antonio-mint, en Mon Jun 23 00:26:38 CEST 2014

source comun.sh

if [[ "$#" -ne 1 ]]; then
  echo "Uso: $0 (id subwiki)"
  exit 1
fi

ID_SUBWIKI=$1

ID_USER1="$(obtenerIdUsuario usuario1)"
ID_USER2="$(obtenerIdUsuario usuario2)"
ID_USER3="$(obtenerIdUsuario usuario3)"

limpiarWiki

editarPagina "$ID_USER1" "La Armada Invencible" "2014-03-05T17:39:31+0100" <<CONTENIDO
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
CONTENIDO

editarPagina "$ID_USER1" "La Armada Invencible" "2014-05-28T14:02:29+0200" <<CONTENIDO
<p><span style=&amp;quot;text-decoration: underline;&amp;quot;><strong>DE DONDE VIENE</strong></span></p>
<p>La denominación «Armada Invencible» es acuñada en Inglaterra, y fue aprovechada por la propaganda anti-española para emplearla en la Leyenda Negra.14 15 Si bien este término ha sido utilizado en la actualidad también en la historiografía española, que ha empleado el término Invencible Inglesa al fallido contraataque británico que tuvo lugar en 1589.</p>
<p><span style=&amp;quot;text-decoration: underline;&amp;quot;><strong>EXPLICACION: ¿QUE ES?</strong></span></p>
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
<p> </p>
CONTENIDO

editarPagina "$ID_USER2" "La Armada Invencible" "2014-05-28T19:42:12+0200" <<CONTENIDO
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>DE DONDE VIENE</strong></span></p>
<p>La denominación «Armada Invencible» es acuñada en Inglaterra, y fue aprovechada por la propaganda anti-española para emplearla en la Leyenda Negra.14 15 Si bien este término ha sido utilizado en la actualidad también en la historiografía española, que ha empleado el término Invencible Inglesa al fallido contraataque británico que tuvo lugar en 1589.</p>
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>EXPLICACION: ¿QUE ES?</strong></span></p>
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
<p> </p>
CONTENIDO

editarPagina "$ID_USER1" "La Armada Invencible" "2014-05-29T23:40:14+0200" <<CONTENIDO
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>DE DONDE VIENE</strong></span></p>
<p>La denominación «Armada Invencible» es acuñada en Inglaterra, y fue aprovechada por la propaganda anti-española para emplearla en la Leyenda Negra.14 15 Si bien este término ha sido utilizado en la actualidad también en la historiografía española, que ha empleado el término Invencible Inglesa al fallido contraataque británico que tuvo lugar en 1589.</p>
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>EXPLICACION: ¿QUE ES?</strong></span></p>
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
<p><span style=&amp;quot;font-size: x-large;&amp;quot;><strong>HISTORIA</strong></span></p>
<p>El combate que la flota enviada por Felipe II sostuvo con la Royal Navy fue tan sólo una de las primeras escaramuzas de una guerra intermitente que comenzó en 1585, y en la que España terminaría por imponerse a Inglaterra en 1604. España se recuperó muy rápidamente del desastre, y Felipe II mandó construir una nueva flota tomando nota de las innovaciones introducidas por los ingleses en la batalla de Gravelinas (1588) y aunándolas con la mayor experiencia española en la construcción de barcos.</p>
<p>A partir de estos hechos y hasta el final de la guerra, España e Inglaterra consiguieron victorias a la par en los combates navales librados por ambos reinos, tanto en la mar como en tierra, con lo que la guerra se mantuvo en un empate de pérdidas de recursos para los países hasta el final. Mientras los ingleses saqueaban las posesiones españolas y no conseguían el objetivo de capturar una flota de Indias, la Armada española se preparó sin mucho éxito para invadir Inglaterra, repelió algún ataque inglés y los corsarios españoles capturaban toneladas de mercancías de barcos ingleses. En 1595 los ingleses (al mando de Drake y Hawkins) atacan infructuosamente San Juan de Puerto Rico y Panamá, encontrando sus comandantes la muerte durante las operaciones.</p>
<p>Felipe II refuerza urgentemente su escuadra, encarga doce nuevos galeones y para 1591, la reconstituida columna vertebral de su armada ya dispone de diecinueve de estos buques, entre los que encontramos tres nuevos, dos capturados a los ingleses, y cuatro veteranos supervivientes de Portugal [...] Alonso de Bazán, hermano del fallecido Álvaro de Bazán, procede contra Thomas Howard con una flota de 55 velas, logrando atrapar a los ingleses entre Punta Delgada y Punta Negra [...] Los ingleses huyen, pero el galeón Revenge [...] es abordado y apresado. [...] En 1595 (los ingleses) preparan la definitiva toma e instalación de una base en Panamá [...] con una flota de 28 barcos. Pero las cosas no fueron bien para los piratas [...] Al mando de Drake, marchan a Panamá, y es allí donde concluye su existencia sir Francis [...] Después de diversas vicisitudes, tan sólo ocho barcos de la expedición lograron regresar a la patria. Tras la contraofensiva inglesa Carlos de Amézquita desembarca en las costas de Cornwall [...] Siembra el Pánico en Penzance y otras localidades cercanas y se retira. [...]<br />Víctor San Juan. La batalla naval de las Dunas. 2007 (págs. 66 y 67)<br />En 1596 los ingleses saquean Cádiz. Al año siguiente intentan destruir en Ferrol una flota española, pero no lo consiguen por culpa de un fuerte temporal, y se marcan el objetivo de capturar la Flota de Indias en las Azores. El almirante Juan Gutiérrez de Garibay engaña a los ingleses y se escapa.</p>
<p>En 1597 los españoles fletan el tercer intento de invasión de Inglaterra con 136 barcos, aprovechando que la flota inglesa está en las Azores, pero una gran tormenta les obliga a volver de nuevo a puerto. En 1600 Newport ataca Jamaica y al año siguiente Parker saquea Portobelo. A partir de ese año las operaciones navales no revisten importancia, hasta que se firma la paz en 1604.</p>
<p>Inglaterra permaneció a raíz de su enfrentamiento con España como una potencia marítima relativamente débil hasta mediados del siglo XVIII, cuando logró arrebatar el rango de segunda potencia naval a la marina francesa.</p>
<p>Por otra parte, es cierto que los nuevos barcos españoles eran más ligeros que los empleados para formar la Grande y Felicísima Armada, y esto les proporcionó una agilidad que, unida a la mejora del sistema de escolta de las flotas de Indias, permitió repeler la mayoría de los ataques de los corsarios y piratas ingleses, holandeses y franceses con un éxito rotundo y sin precedentes. La constatación de las grandes mejoras introducidas se deriva del hecho de que España fue capaz de transportar con total éxito durante la década de 1590 tres veces más cantidad de oro y plata de América que durante las décadas anteriores. De hecho, una flota pirata inglesa al mando de John Hawkins, enviada con el objeto de capturar la flota del tesoro española en 1590, fue totalmente derrotada por los buques de escolta.</p>
<p>La reflexión del historiador y diplomático estadounidense Garret Mattingly es esclarecedora:</p>
<p>[...] el ataque inglés a Portugal en 1589 terminó con el más rotundo de los fracasos, la guerra continuó todavía durante 14 años más, es decir, de hecho continuó mientras vivió la reina Isabel, para terminar en algo así como una retirada. Según algunos historiadores, la derrota de la Armada Invencible «marca el ocaso del imperio colonial español y el comienzo del británico». Resulta difícil comprender el por qué del razonamiento. En 1603 España no había abandonado a Inglaterra ni uno sólo de sus dominios de ultramar, mientras que la colonización inglesa en Virginia tuvo que ser aplazada de momento. La campaña de la Invencible tampoco «transfirió el dominio de los mares de España a Inglaterra»... La derrota de la Invencible no significó el fin de la marina española, sino su comienzo. Los ingleses podían invadir la costa española, pero no bloquearla. Drake y Hawkins soñaban con someter a Felipe impidiendo la llegada de las riquezas del Nuevo Mundo, pero el caso es que llegaron más tesoros de América a España desde el 1588 al 1603 que en ningún otro período de quince años de la historia española.<br />Garret Mattingly. La Armada Invencible. 1961. Grijalbo (pág. 465)<br />Por su parte, el doctor Rodríguez González, experto en Historia naval española también aborda la cuestión:</p>
<p>[...] creemos que basta conocer con algún detalle el tratado de paz firmado por entonces en Londres y Madrid para comprobar hasta qué punto la pretendida victoria inglesa brilla totalmente por su ausencia y es más una reelaboración de la historiografía victoriana del siglo XIX, que quiso adelantar nada menos que al siglo XVI la evidente hegemonía británica en los mares conseguida a finales del XVIII y comienzos del XIX [...] es cierto que los ingleses pudieron sentirse orgullosos de que ellos, una potencia hasta entonces considerada mediana, pudieran hacer frente y hasta ocasionar graves contratiempos a una potencia mundial como era la monarquía de Felipe II. Pero una cosa es haber sobrevivido, que no era poco, ciertamente, y otra, muy diferente, el haber ganado la guerra y con ella, el «Tridente de Neptuno».<br />Agustín Ramón Rodríguez González. Victorias por mar de los españoles. Biblioteca de Historia, Grafite Ediciones, 2006 (pp. 89–90)</p>
CONTENIDO

editarPagina "$ID_USER1" "La Armada Invencible" "2014-06-05T00:50:18+0200" <<CONTENIDO
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>DE DONDE VIENE</strong></span></p>
<p>La denominación «Armada Invencible» es acuñada en Inglaterra, y fue aprovechada por la propaganda anti-española para emplearla en la Leyenda Negra.14 15 Si bien este término ha sido utilizado en la actualidad también en la historiografía española, que ha empleado el término Invencible Inglesa al fallido contraataque británico que tuvo lugar en 1589.</p>
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>EXPLICACION: ¿QUE ES?</strong></span></p>
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
<p><span style=&amp;quot;font-size: x-large;&amp;quot;><strong>HISTORIA</strong></span></p>
<p>El combate que la flota enviada por Felipe II sostuvo con la Royal Navy fue tan sólo una de las primeras escaramuzas de una guerra intermitente que comenzó en 1585, y en la que España terminaría por imponerse a Inglaterra en 1604. España se recuperó muy rápidamente del desastre, y Felipe II mandó construir una nueva flota tomando nota de las innovaciones introducidas por los ingleses en la batalla de Gravelinas (1588) y aunándolas con la mayor experiencia española en la construcción de barcos.</p>
<p>A partir de estos hechos y hasta el final de la guerra, España e Inglaterra consiguieron victorias a la par en los combates navales librados por ambos reinos, tanto en la mar como en tierra, con lo que la guerra se mantuvo en un empate de pérdidas de recursos para los países hasta el final. Mientras los ingleses saqueaban las posesiones españolas y no conseguían el objetivo de capturar una flota de Indias, la Armada española se preparó sin mucho éxito para invadir Inglaterra, repelió algún ataque inglés y los corsarios españoles capturaban toneladas de mercancías de barcos ingleses. En 1595 los ingleses (al mando de Drake y Hawkins) atacan infructuosamente San Juan de Puerto Rico y Panamá, encontrando sus comandantes la muerte durante las operaciones.</p>
<p>Felipe II refuerza urgentemente su escuadra, encarga doce nuevos galeones y para 1591, la reconstituida columna vertebral de su armada ya dispone de diecinueve de estos buques, entre los que encontramos tres nuevos, dos capturados a los ingleses, y cuatro veteranos supervivientes de Portugal [...] Alonso de Bazán, hermano del fallecido Álvaro de Bazán, procede contra Thomas Howard con una flota de 55 velas, logrando atrapar a los ingleses entre Punta Delgada y Punta Negra [...] Los ingleses huyen, pero el galeón Revenge [...] es abordado y apresado. [...] En 1595 (los ingleses) preparan la definitiva toma e instalación de una base en Panamá [...] con una flota de 28 barcos. Pero las cosas no fueron bien para los piratas [...] Al mando de Drake, marchan a Panamá, y es allí donde concluye su existencia sir Francis [...] Después de diversas vicisitudes, tan sólo ocho barcos de la expedición lograron regresar a la patria. Tras la contraofensiva inglesa Carlos de Amézquita desembarca en las costas de Cornwall [...] Siembra el Pánico en Penzance y otras localidades cercanas y se retira. [...]<br />Víctor San Juan. La batalla naval de las Dunas. 2007 (págs. 66 y 67)<br />En 1596 los ingleses saquean Cádiz. Al año siguiente intentan destruir en Ferrol una flota española, pero no lo consiguen por culpa de un fuerte temporal, y se marcan el objetivo de capturar la Flota de Indias en las Azores. El almirante Juan Gutiérrez de Garibay engaña a los ingleses y se escapa.</p>
<p>En 1597 los españoles fletan el tercer intento de invasión de Inglaterra con 136 barcos, aprovechando que la flota inglesa está en las Azores, pero una gran tormenta les obliga a volver de nuevo a puerto. En 1600 Newport ataca Jamaica y al año siguiente Parker saquea Portobelo. A partir de ese año las operaciones navales no revisten importancia, hasta que se firma la paz en 1604.</p>
<p>Inglaterra permaneció a raíz de su enfrentamiento con España como una potencia marítima relativamente débil hasta mediados del siglo XVIII, cuando logró arrebatar el rango de segunda potencia naval a la marina francesa.</p>
<p>Por otra parte, es cierto que los nuevos barcos españoles eran más ligeros que los empleados para formar la Grande y Felicísima Armada, y esto les proporcionó una agilidad que, unida a la mejora del sistema de escolta de las flotas de Indias, permitió repeler la mayoría de los ataques de los corsarios y piratas ingleses, holandeses y franceses con un éxito rotundo y sin precedentes. La constatación de las grandes mejoras introducidas se deriva del hecho de que España fue capaz de transportar con total éxito durante la década de 1590 tres veces más cantidad de oro y plata de América que durante las décadas anteriores. De hecho, una flota pirata inglesa al mando de John Hawkins, enviada con el objeto de capturar la flota del tesoro española en 1590, fue totalmente derrotada por los buques de escolta.</p>
<p>La reflexión del historiador y diplomático estadounidense Garret Mattingly es esclarecedora:</p>
<p>[...] el ataque inglés a Portugal en 1589 terminó con el más rotundo de los fracasos, la guerra continuó todavía durante 14 años más, es decir, de hecho continuó mientras vivió la reina Isabel, para terminar en algo así como una retirada. Según algunos historiadores, la derrota de la Armada Invencible «marca el ocaso del imperio colonial español y el comienzo del británico». Resulta difícil comprender el por qué del razonamiento. En 1603 España no había abandonado a Inglaterra ni uno sólo de sus dominios de ultramar, mientras que la colonización inglesa en Virginia tuvo que ser aplazada de momento. La campaña de la Invencible tampoco «transfirió el dominio de los mares de España a Inglaterra»... La derrota de la Invencible no significó el fin de la marina española, sino su comienzo. Los ingleses podían invadir la costa española, pero no bloquearla. Drake y Hawkins soñaban con someter a Felipe impidiendo la llegada de las riquezas del Nuevo Mundo, pero el caso es que llegaron más tesoros de América a España desde el 1588 al 1603 que en ningún otro período de quince años de la historia española.<br />Garret Mattingly. La Armada Invencible. 1961. Grijalbo (pág. 465)<br />Por su parte, el doctor Rodríguez González, experto en Historia naval española también aborda la cuestión:</p>
<p>[...] creemos que basta conocer con algún detalle el tratado de paz firmado por entonces en Londres y Madrid para comprobar hasta qué punto la pretendida victoria inglesa brilla totalmente por su ausencia y es más una reelaboración de la historiografía victoriana del siglo XIX, que quiso adelantar nada menos que al siglo XVI la evidente hegemonía británica en los mares conseguida a finales del XVIII y comienzos del XIX [...] es cierto que los ingleses pudieron sentirse orgullosos de que ellos, una potencia hasta entonces considerada mediana, pudieran hacer frente y hasta ocasionar graves contratiempos a una potencia mundial como era la monarquía de Felipe II. Pero una cosa es haber sobrevivido, que no era poco, ciertamente, y otra, muy diferente, el haber ganado la guerra y con ella, el «Tridente de Neptuno».<br />Agustín Ramón Rodríguez González. Victorias por mar de los españoles. Biblioteca de Historia, Grafite Ediciones, 2006 (pp. 89–90)</p>
<p><img style=&amp;quot;display: block; margin-left: auto; margin-right: auto;&amp;quot; src=&amp;quot;http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Routes_of_the_Spanish_Armada-es.svg/1200px-Routes_of_the_Spanish_Armada-es.svg.png&amp;quot; alt=&amp;quot;Armada Invencible&amp;quot; width=&amp;quot;327&amp;quot; height=&amp;quot;600&amp;quot; /></p>
CONTENIDO

editarPagina "$ID_USER3" "La Armada Invencible" "2014-06-05T00:53:33+0200" <<CONTENIDO
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>DE DONDE VIENE</strong></span></p>
<p>La denominación «Armada Invencible» es acuñada en Inglaterra, y fue aprovechada por la propaganda anti-española para emplearla en la Leyenda Negra.14 15 Si bien este término ha sido utilizado en la actualidad también en la historiografía española, que ha empleado el término Invencible Inglesa al fallido contraataque británico que tuvo lugar en 1589.</p>
<p><span style=&amp;quot;text-decoration: underline; font-size: large;&amp;quot;><strong>EXPLICACION: ¿QUE ES?</strong></span></p>
<p>Armada Invencible es un término de origen inglés,6 para referirse a la Empresa de Inglaterra de 1588 proyectada por el monarca español Felipe II para destronar a Isabel I e invadir Inglaterra. El ataque tuvo lugar en el contexto de la Guerra anglo-española de 1585-1604.7 El ataque fracasó pero la guerra se extendió 16 años más y terminó con el Tratado de Londres de 1604, favorable a España.</p>
<p>Felipe II decidió articular el ataque conjuntamente, y de manera compleja, desde Portugal y desde las posesiones españolas en los actuales Países Bajos. Se armó una gran flota en puertos españoles que recibió el nombre de Grande y Felicísima Armada. Las naves enviadas desde Portugal (pues Felipe también gobernaba allí) participarían en el combate, mientras que las fuerzas españolas que salieran simultáneamente desde Países Bajos, con los Tercios de Flandes, se encontrarían entre el Canal de la Mancha y el Mar del Norte con las que habían salido de la península, con el objetivo de desembarcar en Inglaterra.8 Esta invasión no pretendía la anexión de las islas británicas al Imperio español, sino la expulsión de Isabel I del trono inglés, y respondía a la ejecución de María Estuardo, la política anti-española de piratería y a la Guerra de Flandes.9 Debía mandarla el almirante de Castilla Álvaro de Bazán, marqués de Santa Cruz, pero murió poco antes de la partida de la flota, siendo sustituido a toda prisa por Alonso Pérez de Guzmán (VII duque de Medina-Sidonia), Grande de España. Estaba compuesta de 127 barcos que partieron de Lisboa, y de ellos, 122 barcos penetraron en el Canal de la Mancha.10</p>
<p>Las turbulentas condiciones meteorológicas en el mar llevaron al naufragios a muchas naves, sin embargo 87 barcos, unas tres cuartas partes, regresaron a España.11 sin haber cumplido su misión de derrotar las fuerzas inglesas y favorecer el ataque desde Flandes.12 13 Al año siguiente Inglaterra intentó aprovechar la ventaja obtenida tras este fracaso de ataque español y realizó su propia flota, la Contraarmada o Invencible inglesa (con una flota aún mayor que la española), resultando en otro absoluto fracaso y devolviendo el statu quo al conflicto.</p>
<p><span style=&amp;quot;font-size: x-large;&amp;quot;><strong>HISTORIA</strong></span></p>
<p>El combate que la flota enviada por Felipe II sostuvo con la Royal Navy fue tan sólo una de las primeras escaramuzas de una guerra intermitente que comenzó en 1585, y en la que España terminaría por imponerse a Inglaterra en 1604. España se recuperó muy rápidamente del desastre, y Felipe II mandó construir una nueva flota tomando nota de las innovaciones introducidas por los ingleses en la batalla de Gravelinas (1588) y aunándolas con la mayor experiencia española en la construcción de barcos.</p>
<p>A partir de estos hechos y hasta el final de la guerra, España e Inglaterra consiguieron victorias a la par en los combates navales librados por ambos reinos, tanto en la mar como en tierra, con lo que la guerra se mantuvo en un empate de pérdidas de recursos para los países hasta el final. Mientras los ingleses saqueaban las posesiones españolas y no conseguían el objetivo de capturar una flota de Indias, la Armada española se preparó sin mucho éxito para invadir Inglaterra, repelió algún ataque inglés y los corsarios españoles capturaban toneladas de mercancías de barcos ingleses. En 1595 los ingleses (al mando de Drake y Hawkins) atacan infructuosamente San Juan de Puerto Rico y Panamá, encontrando sus comandantes la muerte durante las operaciones.</p>
<p>Felipe II refuerza urgentemente su escuadra, encarga doce nuevos galeones y para 1591, la reconstituida columna vertebral de su armada ya dispone de diecinueve de estos buques, entre los que encontramos tres nuevos, dos capturados a los ingleses, y cuatro veteranos supervivientes de Portugal [...] Alonso de Bazán, hermano del fallecido Álvaro de Bazán, procede contra Thomas Howard con una flota de 55 velas, logrando atrapar a los ingleses entre Punta Delgada y Punta Negra [...] Los ingleses huyen, pero el galeón Revenge [...] es abordado y apresado. [...] En 1595 (los ingleses) preparan la definitiva toma e instalación de una base en Panamá [...] con una flota de 28 barcos. Pero las cosas no fueron bien para los piratas [...] Al mando de Drake, marchan a Panamá, y es allí donde concluye su existencia sir Francis [...] Después de diversas vicisitudes, tan sólo ocho barcos de la expedición lograron regresar a la patria. Tras la contraofensiva inglesa Carlos de Amézquita desembarca en las costas de Cornwall [...] Siembra el Pánico en Penzance y otras localidades cercanas y se retira. [...]<br />Víctor San Juan. La batalla naval de las Dunas. 2007 (págs. 66 y 67)<br />En 1596 los ingleses saquean Cádiz. Al año siguiente intentan destruir en Ferrol una flota española, pero no lo consiguen por culpa de un fuerte temporal, y se marcan el objetivo de capturar la Flota de Indias en las Azores. El almirante Juan Gutiérrez de Garibay engaña a los ingleses y se escapa.</p>
<p>En 1597 los españoles fletan el tercer intento de invasión de Inglaterra con 136 barcos, aprovechando que la flota inglesa está en las Azores, pero una gran tormenta les obliga a volver de nuevo a puerto. En 1600 Newport ataca Jamaica y al año siguiente Parker saquea Portobelo. A partir de ese año las operaciones navales no revisten importancia, hasta que se firma la paz en 1604.</p>
<p>Inglaterra permaneció a raíz de su enfrentamiento con España como una potencia marítima relativamente débil hasta mediados del siglo XVIII, cuando logró arrebatar el rango de segunda potencia naval a la marina francesa.</p>
<p>Por otra parte, es cierto que los nuevos barcos españoles eran más ligeros que los empleados para formar la Grande y Felicísima Armada, y esto les proporcionó una agilidad que, unida a la mejora del sistema de escolta de las flotas de Indias, permitió repeler la mayoría de los ataques de los corsarios y piratas ingleses, holandeses y franceses con un éxito rotundo y sin precedentes. La constatación de las grandes mejoras introducidas se deriva del hecho de que España fue capaz de transportar con total éxito durante la década de 1590 tres veces más cantidad de oro y plata de América que durante las décadas anteriores. De hecho, una flota pirata inglesa al mando de John Hawkins, enviada con el objeto de capturar la flota del tesoro española en 1590, fue totalmente derrotada por los buques de escolta.</p>
<p>La reflexión del historiador y diplomático estadounidense Garret Mattingly es esclarecedora:</p>
<p>[...] el ataque inglés a Portugal en 1589 terminó con el más rotundo de los fracasos, la guerra continuó todavía durante 14 años más, de hecho continuó mientras vivió la reina Isabel, para terminar en algo así como una retirada. Según algunos historiadores, la derrota de la Armada Invencible «marca el ocaso del imperio colonial español y el comienzo del británico». Resulta difícil comprender el por qué del razonamiento. En 1603 España no había abandonado a Inglaterra ni uno sólo de sus dominios de ultramar, mientras que la colonización inglesa en Virginia tuvo que ser aplazada de momento. La campaña de la Invencible tampoco «transfirió el dominio de los mares de España a Inglaterra»... La derrota de la Invencible no significó el fin de la marina española, sino su comienzo. Los ingleses podían invadir la costa española, pero no bloquearla. Drake y Hawkins soñaban con someter a Felipe impidiendo la llegada de las riquezas del Nuevo Mundo, pero el caso es que llegaron más tesoros de América a España desde el 1588 al 1603 que en ningún otro período de quince años de la historia española.<br />Garret Mattingly. La Armada Invencible. 1961. Grijalbo (pág. 465)<br />Por su parte, el doctor Rodríguez González, experto en Historia naval española también aborda la cuestión:</p>
<p>[...] creemos que basta conocer con algún detalle el tratado de paz firmado por entonces en Londres y Madrid para comprobar hasta qué punto la pretendida victoria inglesa brilla totalmente por su ausencia y es más una reelaboración de la historiografía victoriana del siglo XIX, que quiso adelantar nada menos que al siglo XVI la evidente hegemonía británica en los mares conseguida a finales del XVIII y comienzos del XIX [...] es cierto que los ingleses pudieron sentirse orgullosos de que ellos, una potencia hasta entonces considerada mediana, pudieran hacer frente y hasta ocasionar graves contratiempos a una potencia mundial como era la monarquía de Felipe II. Pero una cosa es haber sobrevivido, que no era poco, ciertamente, y otra, muy diferente, el haber ganado la guerra y con ella, el «Tridente de Neptuno».<br />Agustín Ramón Rodríguez González. Victorias por mar de los españoles. Biblioteca de Historia, Grafite Ediciones, 2006 (pp. 89–90)</p>
<p><img style=&amp;quot;display: block; margin-left: auto; margin-right: auto;&amp;quot; src=&amp;quot;http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Routes_of_the_Spanish_Armada-es.svg/1200px-Routes_of_the_Spanish_Armada-es.svg.png&amp;quot; alt=&amp;quot;Armada Invencible&amp;quot; width=&amp;quot;327&amp;quot; height=&amp;quot;600&amp;quot; /></p>
CONTENIDO


visitarPaginasWiki
